---
- hosts: all
  become: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Delete file
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Creating a file with content
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
          <head>
          <title>Hello World</title>
          </head>
          <body>
          <h1>Hello World!</h1>
          </body>
          </html
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded