---
- hosts: web
  tasks:
    - name: install nginx
      apt: name=nginx state=latest
    - name: Copy index.html file
      template:
        src: ./index.html
        dest: /usr/share/nginx/html/index.html
        owner: nginx
        group: nginx
        mode: '0644'
    - name: start nginx
      service:
          name: nginx
          state: started
