---
- hosts: all
  become: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Delete file
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Creating a file with content
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
          <head>
          <title>Hello World</title>
          </head>
          <body>
          <h1>Hello World!</h1>
          </body>
          </html
      notify: restart nginx
    - name: Create the private key
      community.crypto.openssl_privatekey:
        path: /registry/certs/tls.key
        size: 4096

    - name: Create certificate signing request (CSR) for self-signed certificate
      community.crypto.openssl_csr_pipe:
        privatekey_path: /registry/certs/tls.key
        common_name: docker-registry
        subject_alt_name:
          - "DNS:docker-registry"
      register: csr

    - name: Create self-signed certificate from CSR
      community.crypto.x509_certificate:
        path: /registry/certs/tls.crt
        csr_content: "{{ csr.csr }}"
        privatekey_path: /registry/certs/tls.crt
        provider: selfsigned
        selfsigned_not_after: +365d # valid for one year
        selfsigned_not_before: "-1d" # valid since yesterday
        selfsigned_digest: "sha256" # this is the default and can be omitted

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted