---
- hosts: all
  become: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Delete file
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Creating a file with content
      copy:
        dest: /var/www/html/index.html
        content: |
          <html>
          <head>
          <title>Hello World</title>
          </head>
          <body>
          <h1>Hello World!</h1>
          </body>
          </html
      notify: restart nginx
    
    - name: Install required packages
      apt:
        name:
          - openssl
        state: present

    - name: Create self-signed SSL certificate
      openssl_certificate:
        path: /etc/ssl/certs/nginx-selfsigned.crt
        privatekey_path: /etc/ssl/private/nginx-selfsigned.key
        state: present
        organization_name: "Your Company"
        country_name: "US"
        email_address: "your_email@example.com"
        force: true

    - name: Create Diffie-Hellman group
      openssl_dhparam:
        path: /etc/ssl/certs/dhparam.pem
        size: 2048
        force: true

    - name: Copy Nginx configuration file
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/default
      notify:
        - restart nginx

    - name: Create a symlink for the Nginx configuration
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted