name: Ansible Configuration
on:
  push:
    branches:
      - master
jobs:
    run-playbooks:
      runs-on: ubuntu-latest
      steps: 
        
        - name: Checkout repository
          uses: actions/checkout@v4.1.2
        - name: Setup SSH 
          shell: bash
          run: |
           eval `ssh-agent -s`
           mkdir -p /home/runner/.ssh/
           touch /home/runner/.ssh/id_rsa
           echo -e "${{secrets.SSH_KEY}}" > /home/runner/.ssh/id_rsa
           chmod 700 /home/runner/.ssh/id_rsa
           ssh-keyscan -t rsa,dsa,ecdsa,ed25519 ${{secrets.SSH_HOST}} >> /home/runner/.ssh/known_hosts
        - name: Run ansible script
          shell: bash 
          run: |
            service ssh status
            cd ./ansible-manifests
            ansible-playbook -vvv --private-key /home/runner/.ssh/id_rsa -i inventory.cfg nginx.yml -b
  